class AppStrings {
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'app_name': 'SafeBuy Nepal',
      'tagline': 'Buy Smart. Stay Safe.',
      'search_hint': 'Search by phone, eSewa ID, or @username...',
      'scam_alert_title': 'Scam Alert',
      'scam_alert_body': 'Multiple reports of fake TikTok sellers in Kathmandu this week. Always verify before paying.',
      'quick_actions': 'Quick Actions',
      'search_seller': 'Search\nSeller',
      'report_fraud': 'Report\nFraud',
      'register_business': 'Register\nBusiness',
      'community_stats': 'Community Stats',
      'sellers_verified': 'Sellers\nVerified',
      'scam_reports': 'Scam\nReports',
      'scams_prevented': 'Scams\nPrevented',
      'how_it_works': 'How It Works',
      'step1_title': 'Search',
      'step1_sub': 'Enter seller phone or username',
      'step2_title': 'Check',
      'step2_sub': 'See trust score and community reports',
      'step3_title': 'Decide',
      'step3_sub': 'Buy confidently or report fraud',
      'no_seller_found': 'No seller found',
      'no_seller_body': 'This seller has not been registered yet. Be cautious before making payment.',
      'report_this_seller': 'Report this seller',
      'home': 'Home',
      'my_business': 'My Business',
      'trusted': 'TRUSTED',
      'unverified': 'UNVERIFIED',
      'high_risk': 'HIGH RISK',
      'select_language': 'Select Language',
      'language_en': 'English',
      'language_ne': 'नेपाली',
      'continue_btn': 'Continue',
      'amount_lost': 'Amount Lost (NPR)',
      'seller_details': 'Seller Details',
      'incident_info': 'Incident Info',
      'evidence': 'Evidence',
      'what_happened': 'What happened?',
      'who_scammed': 'Who scammed you?',
      'evidence_upload': 'Evidence Upload',
    },
    'ne': {
      'app_name': 'SafeBuy Nepal',
      'tagline': 'बुद्धिमानीले किन्नुहोस्। सुरक्षित रहनुहोस्।',
      'search_hint': 'फोन, eSewa ID, वा @username खोज्नुहोस्...',
      'scam_alert_title': 'घोटाला अलर्ट',
      'scam_alert_body': 'यस हप्ता काठमाडौंमा नक्कली TikTok विक्रेताहरूको धेरै रिपोर्टहरू। भुक्तानी गर्नु अघि सधैं प्रमाणित गर्नुहोस्।',
      'quick_actions': 'द्रुत कार्यहरू',
      'search_seller': 'विक्रेता\nखोज्नुहोस्',
      'report_fraud': 'धोखाधडी\nरिपोर्ट',
      'register_business': 'व्यवसाय\nदर्ता',
      'community_stats': 'समुदाय तथ्याङ्क',
      'sellers_verified': 'विक्रेता\nप्रमाणित',
      'scam_reports': 'घोटाला\nरिपोर्ट',
      'scams_prevented': 'घोटाला\nरोकियो',
      'how_it_works': 'कसरी काम गर्छ',
      'step1_title': 'खोज्नुहोस्',
      'step1_sub': 'विक्रेताको फोन वा नाम लेख्नुहोस्',
      'step2_title': 'जाँच गर्नुहोस्',
      'step2_sub': 'ट्रस्ट स्कोर र रिपोर्टहरू हेर्नुहोस्',
      'step3_title': 'निर्णय गर्नुहोस्',
      'step3_sub': 'आत्मविश्वासका साथ किन्नुहोस् वा रिपोर्ट गर्नुहोस्',
      'no_seller_found': 'कुनै विक्रेता भेटिएन',
      'no_seller_body': 'यो विक्रेता अझै दर्ता भएको छैन। भुक्तानी गर्नु अघि सावधान रहनुहोस्।',
      'report_this_seller': 'यो विक्रेता रिपोर्ट गर्नुहोस्',
      'home': 'गृहपृष्ठ',
      'my_business': 'मेरो व्यवसाय',
      'trusted': 'विश्वसनीय',
      'unverified': 'अप्रमाणित',
      'high_risk': 'उच्च जोखिम',
      'select_language': 'भाषा छान्नुहोस्',
      'language_en': 'English',
      'language_ne': 'नेपाली',
      'continue_btn': 'जारी राख्नुहोस्',
      'amount_lost': 'गुमेको रकम (रु)',
      'seller_details': 'विक्रेता विवरण',
      'incident_info': 'घटना जानकारी',
      'evidence': 'प्रमाण',
      'what_happened': 'के भयो?',
      'who_scammed': 'कसले ठग्यो?',
      'evidence_upload': 'प्रमाण अपलोड',
    },
  };

  static String get(String key, String lang) {
    return _strings[lang]?[key] ?? _strings['en']?[key] ?? key;
  }
}
