/// SafeBuy Nepal — Bilingual String Repository
/// USAGE: AppStrings.get('key', lang)
/// lang = 'en' for English, 'ne' for Nepali (Devanagari)
abstract final class AppStrings {
  static const _en = <String, String>{
    // ── App general ──────────────────────────────────────────────────────────────
    'app_name'        : 'SafeBuy Nepal',
    'tagline'         : 'Buy Smart. Stay Safe.',
    'tagline_ne'      : 'बुद्धिमानीले किन्नुहोस्।',
    'ok'              : 'OK',
    'cancel'          : 'Cancel',
    'retry'           : 'Retry',
    'done'            : 'Done',
    'next'            : 'Next',
    'back'            : 'Back',
    'skip'            : 'Skip',
    'save'            : 'Save',
    'submit'          : 'Submit',
    'continue_btn'    : 'Continue',
    'loading'         : 'Loading...',
    'error_generic'   : 'Something went wrong. Please try again.',
    'error_network'   : 'No internet connection. Please check your network.',
    'error_permission': 'Permission denied.',

    // ── Onboarding ───────────────────────────────────────────────────────────────
    'onboard1_title'  : 'Verify Before You Pay',
    'onboard1_body'   : 'Search any seller by phone, eSewa ID, or social handle and see their SafeBuy trust score before making a payment.',
    'onboard2_title'  : 'Report Fraud, Protect Others',
    'onboard2_body'   : 'Experienced a scam? File a report with evidence. Your report protects thousands of other Nepali buyers.',
    'onboard3_title'  : 'Build Your Business Trust',
    'onboard3_body'   : 'Register your business and earn a verified badge. Buyers trust sellers with a high SafeBuy score.',
    'onboard4_title'  : 'Anti-Bot Protected Reviews',
    'onboard4_body'   : 'Our 6-layer anti-bot system prevents fake reviews: account age checks, rate limiting, text similarity detection, review cooldowns, and authenticity scoring. Every review is verified genuine.',
    'get_started'     : 'Get Started',

    // ── Auth ─────────────────────────────────────────────────────────────────────
    'phone_auth_title'      : 'Verify Your Phone',
    'phone_auth_subtitle'   : 'We\'ll send a one-time code to your number.',
    'phone_hint'            : 'Phone Number',
    'phone_prefix'          : '+977',
    'send_otp'              : 'Send OTP',
    'otp_title'             : 'Enter OTP',
    'otp_subtitle'          : 'Enter the 6-digit code sent to',
    'otp_resend'            : 'Resend OTP',
    'otp_resend_in'         : 'Resend in',
    'verify'                : 'Verify',
    'privacy_note'          : 'Your number is only used for identity verification. We never share it.',
    'setup_title'           : 'Set Up Your Profile',
    'full_name'             : 'Full Name',
    'i_am_buyer'            : 'I\'m a Buyer',
    'i_am_buyer_sub'        : 'I want to verify sellers and stay safe',
    'i_am_seller'           : 'I\'m a Seller',
    'i_am_seller_sub'       : 'I want to build my trust rating',

    // ── Home ─────────────────────────────────────────────────────────────────────
    'search_hint'           : 'Search by phone, eSewa ID, or @username...',
    'scam_alert_title'      : 'Scam Alert',
    'scam_alert_body'       : 'Multiple reports of fake TikTok sellers in Kathmandu this week. Always verify before paying.',
    'quick_actions'         : 'Quick Actions',
    'search_seller'         : 'Search\nSeller',
    'report_fraud'          : 'Report\nFraud',
    'register_business'     : 'Register\nBusiness',
    'community_stats'       : 'Community Stats',
    'sellers_verified'      : 'Sellers\nVerified',
    'scam_reports'          : 'Scam\nReports',
    'scams_prevented'       : 'Scams\nPrevented',
    'how_it_works'          : 'How It Works',
    'step1_title'           : 'Search',
    'step1_sub'             : 'Enter seller phone, eSewa ID, or username',
    'step2_title'           : 'Check',
    'step2_sub'             : 'See trust score and community reports',
    'step3_title'           : 'Decide',
    'step3_sub'             : 'Buy confidently or report fraud',
    'no_seller_found'       : 'No Seller Found',
    'no_seller_body'        : 'This seller is not in our database yet. Be cautious before making any payment.',
    'report_this_seller'    : 'Report This Seller',
    'home'                  : 'Home',
    'my_business'           : 'My Business',

    // ── Trust badges ─────────────────────────────────────────────────────────────
    'trusted'               : 'TRUSTED',
    'unverified'            : 'UNVERIFIED',
    'high_risk'             : 'HIGH RISK',
    'trust_score'           : 'Trust Score',
    'verified_badge'        : 'Verified',
    'reports_count'         : 'Reports',
    'reviews_count'         : 'Reviews',
    'orders_count'          : 'Orders',

    // ── Report form ───────────────────────────────────────────────────────────────
    'who_scammed'           : 'Who scammed you?',
    'who_scammed_sub'       : 'Enter any identifier you know about the seller',
    'phone_number'          : 'Phone Number *',
    'esewa_id'              : 'eSewa / Khalti ID',
    'social_handle'         : 'Social Media Handle',
    'platform'              : 'Platform',
    'what_happened'         : 'What happened?',
    'what_happened_sub'     : 'Describe the incident in detail',
    'amount_lost'           : 'Amount Lost (NPR)',
    'incident_type'         : 'Incident Type *',
    'description'           : 'Description *',
    'description_hint'      : 'Describe what happened in detail (minimum 50 characters)...',
    'incident_date'         : 'Date of Incident',
    'declaration_check'     : 'I confirm this report is truthful and based on my genuine personal experience.',
    'evidence_upload'       : 'Evidence Upload',
    'evidence_sub'          : 'Screenshots help verify your report faster',
    'payment_screenshot'    : 'Payment Screenshot',
    'chat_screenshot'       : 'Chat Screenshot',
    'add_screenshot'        : 'Tap to add screenshot',
    'evidence_types'        : 'Payment proof, chat screenshots, product photos',
    'report_submitted'      : 'Report Submitted!',
    'report_submitted_body' : 'Your report has been received. Our team will review it within 2-3 working days. Thank you for protecting the community.',
    'report_id_label'       : 'Your Report ID',
    'seller_details'        : 'Seller Details',
    'incident_info'         : 'Incident Info',
    'evidence'              : 'Evidence',

    // ── Business registration ─────────────────────────────────────────────────────
    'reg_title'             : 'Register Your Business',
    'reg_step1_title'       : 'Business Info',
    'reg_step2_title'       : 'Social Media',
    'reg_step3_title'       : 'Confirm',
    'business_name'         : 'Business Name *',
    'business_category'     : 'Category *',
    'business_description'  : 'Business Description',
    'business_description_hint': 'Tell buyers about your business (50-500 characters)...',
    'esewa_recommended'     : 'eSewa ID (recommended)',
    'tiktok_handle'         : 'TikTok Handle',
    'instagram_handle'      : 'Instagram Handle',
    'facebook_page'         : 'Facebook Page',
    'declaration_business'  : 'I confirm this information is accurate and I am the authorised owner of these accounts.',
    'reg_submitted'         : 'Registration Submitted!',
    'reg_submitted_body'    : 'Your business has been submitted for verification. You\'ll receive a trust score within 48 hours.',

    // ── Dashboard ─────────────────────────────────────────────────────────────────
    'dashboard_title'       : 'Business Dashboard',
    'verification_steps'    : 'Verification Checklist',
    'recent_activity'       : 'Recent Activity',
    'your_reports'          : 'Reports Against You',
    'respond'               : 'Respond',
    'share_profile'         : 'Share Profile',
    'request_verification'  : 'Request Verification',
    'profile_views_today'   : 'Profile Views Today',
    'avg_rating'            : 'Average Rating',

    // ── Language ──────────────────────────────────────────────────────────────────
    'select_language'       : 'Select Language / भाषा छान्नुहोस्',
    'continue_english'      : 'Continue in English',
    'continue_nepali'       : 'नेपालीमा जारी राख्नुहोस्',

    // ── Chatbot ───────────────────────────────────────────────────────────────────
    'chatbot_label'         : 'Help',
    'chatbot_title'         : 'SafeBuy Assistant',
    'chatbot_online'        : 'Online',
    'chatbot_greeting'      : 'Hello! 👋 I\'m the SafeBuy Nepal assistant. Choose a topic below or type your question.',
    'chatbot_fallback'      : 'I didn\'t understand that. Please select one of the options below or rephrase your question.',
    'chatbot_type_hint'     : 'Type your question...',
    'quick_questions'       : 'Quick questions:',

    // ── Incident type display ──────────────────────────────────────────────────────
    'inc_no_delivery'       : 'Item Not Delivered',
    'inc_wrong_item'        : 'Wrong Item Sent',
    'inc_fake_product'      : 'Fake / Counterfeit Product',
    'inc_payment_issue'     : 'Payment Taken, No Response',
    'inc_impersonation'     : 'Account Impersonation',
    'inc_other'             : 'Other',

    // ── Popup messages ────────────────────────────────────────────────────────────
    'success_report'        : 'Report submitted successfully!',
    'success_review'        : 'Review submitted!',
    'success_kyc'           : 'KYC submitted for review',
    'success_signout'       : 'Signed out successfully',
    'warning_auth_required' : 'Sign in to continue',
    'error_upload'          : 'Upload failed. Please check your connection and try again.',
    'error_load'            : 'Could not load data. Please try again.',

    // ── KYC ───────────────────────────────────────────────────────────────────────
    'kyc_title'             : 'Get SafeBuy Verified',
    'kyc_subtitle'          : 'Protect your business and build buyer trust',
    'kyc_start'             : 'Start Verification',
    'kyc_tier_basic'        : 'Basic',
    'kyc_tier_verified'     : 'Verified',
    'kyc_tier_premium'      : 'Premium',
    'kyc_link_gmail'        : 'Link Gmail Account',
    'kyc_upload_qr'         : 'Upload your eSewa QR code',
    'kyc_selfie_title'      : 'Selfie with Citizenship Card',
    'kyc_pan_title'         : 'PAN Card Upload',
    'kyc_location_title'    : 'Business Location Photos',
    'kyc_submitted'         : 'KYC Submitted for Review',
    'kyc_review_time'       : 'Our team will review within 24-48 hours',
    'kyc_qr_locked'         : 'Payment QR — Locked by SafeBuy Nepal',
    'kyc_request_qr_change' : 'Request QR Change',

    // ── Leaderboard ───────────────────────────────────────────────────────────────
    'leaderboard_title'     : 'Monthly Leaderboard',
    'leaderboard_subtitle'  : 'Top verified sellers this month',
    'leaderboard_this_month': 'This Month',
    'leaderboard_last_month': 'Last Month',
    'leaderboard_all_time'  : 'All Time',
    'leaderboard_empty'     : 'No rankings available yet for this period',

    // ── Reviews ───────────────────────────────────────────────────────────────────
    'review_write'          : 'Write a Review',
    'review_product_name'   : 'What did you purchase?',
    'review_rating'         : 'Your rating',
    'review_experience'     : 'Overall experience',
    'review_verified'       : 'Verified Purchase',
    'review_top'            : 'Top Review',

    // ── Guide ─────────────────────────────────────────────────────────────────────
    'guide_title'           : 'How It Works',
    'guide_for_buyers'      : 'For Buyers',
    'guide_for_sellers'     : 'For Sellers',
    'guide_about'           : 'About SafeBuy',

    // ── Scam news ─────────────────────────────────────────────────────────────────
    'scam_news_title'       : 'Scam Reports Nepal',
    'scam_news_cases'       : 'Cases',
    'scam_news_stats'       : 'Statistics',
    'scam_news_rights'      : 'Your Rights',
    'scam_news_read_more'   : 'Read More',
    'scam_news_show_less'   : 'Show Less',
    'scam_news_lesson'      : 'Lesson',

    // ── Search ────────────────────────────────────────────────────────────────────
    'search_title'          : 'Verify a Seller',
    'search_member_since'   : 'Member since',
    'search_verified_until' : 'Verified until',
    'search_overdue'        : 'Re-verification Overdue',
    'search_view_profile'   : 'View Full Profile',
    'search_report_seller'  : 'Report This Seller',
    'search_sign_in_report' : 'Sign in to Report',
    'search_not_found'      : 'No seller found with this information',
  };

  static const _ne = <String, String>{
    // ── App general ──────────────────────────────────────────────────────────────
    'app_name'        : 'SafeBuy Nepal',
    'tagline'         : 'बुद्धिमानीले किन्नुहोस्। सुरक्षित रहनुहोस्।',
    'ok'              : 'ठीक छ',
    'cancel'          : 'रद्द गर्नुहोस्',
    'retry'           : 'पुनः प्रयास',
    'done'            : 'सम्पन्न',
    'next'            : 'अर्को',
    'back'            : 'पछाडि',
    'skip'            : 'छोड्नुहोस्',
    'save'            : 'सुरक्षित',
    'submit'          : 'पेश गर्नुहोस्',
    'continue_btn'    : 'जारी राख्नुहोस्',
    'loading'         : 'लोड हुँदैछ...',
    'error_generic'   : 'केही गलत भयो। कृपया पुनः प्रयास गर्नुहोस्।',
    'error_network'   : 'इन्टरनेट जडान छैन। कृपया आफ्नो नेटवर्क जाँच गर्नुहोस्।',
    'error_permission': 'अनुमति अस्वीकृत।',

    // ── Onboarding ───────────────────────────────────────────────────────────────
    'onboard1_title'  : 'भुक्तानी गर्नु अघि प्रमाणित गर्नुहोस्',
    'onboard1_body'   : 'भुक्तानी गर्नु अघि फोन, eSewa ID, वा सोसल ह्यान्डलद्वारा कुनै पनि विक्रेता खोज्नुहोस् र उनीहरूको SafeBuy ट्रस्ट स्कोर हेर्नुहोस्।',
    'onboard2_title'  : 'धोखाधडी रिपोर्ट गर्नुहोस्, अरूलाई बचाउनुहोस्',
    'onboard2_body'   : 'घोटालामा परेकाछौ? प्रमाणसहित रिपोर्ट गर्नुहोस्। तपाईंको रिपोर्टले हजारौं नेपाली खरिदारहरूलाई जोगाउँछ।',
    'onboard3_title'  : 'आफ्नो व्यवसायको विश्वास बनाउनुहोस्',
    'onboard3_body'   : 'आफ्नो व्यवसाय दर्ता गर्नुहोस् र प्रमाणित ब्याज पाउनुहोस्। उच्च SafeBuy स्कोर भएका विक्रेतालाई खरिदारहरूले विश्वास गर्छन्।',
    'onboard4_title'  : 'एन्टी-बोट सुरक्षित समीक्षा',
    'onboard4_body'   : 'हाम्रो ६-तह एन्टी-बोट प्रणालीले नक्कली समीक्षा रोक्छ: खाता उमेर जाँच, दर सीमा, पाठ समानता पत्ता लगाउने, समीक्षा कूलडाउन, र प्रमाणिकता स्कोरिङ। हरेक समीक्षा प्रमाणित छ।',
    'get_started'     : 'सुरु गर्नुहोस्',

    // ── Auth ─────────────────────────────────────────────────────────────────────
    'phone_auth_title'      : 'फोन प्रमाणित गर्नुहोस्',
    'phone_auth_subtitle'   : 'हामी तपाईंको नम्बरमा एक पटकको कोड पठाउनेछौं।',
    'phone_hint'            : 'फोन नम्बर',
    'phone_prefix'          : '+977',
    'send_otp'              : 'OTP पठाउनुहोस्',
    'otp_title'             : 'OTP प्रविष्ट गर्नुहोस्',
    'otp_subtitle'          : 'यो नम्बरमा पठाइएको ६-अंकको कोड:',
    'otp_resend'            : 'OTP पुनः पठाउनुहोस्',
    'otp_resend_in'         : 'यति समयमा पुनः पठाउनुहोस्',
    'verify'                : 'प्रमाणित गर्नुहोस्',
    'privacy_note'          : 'तपाईंको नम्बर केवल पहिचान प्रमाणीकरणका लागि प्रयोग गरिन्छ।',
    'setup_title'           : 'प्रोफाइल सेटअप गर्नुहोस्',
    'full_name'             : 'पूरा नाम',
    'i_am_buyer'            : 'म खरिदार हुँ',
    'i_am_buyer_sub'        : 'विक्रेता प्रमाणित गरी सुरक्षित रहन चाहन्छु',
    'i_am_seller'           : 'म विक्रेता हुँ',
    'i_am_seller_sub'       : 'आफ्नो ट्रस्ट रेटिङ बनाउन चाहन्छु',

    // ── Home ─────────────────────────────────────────────────────────────────────
    'search_hint'           : 'फोन, eSewa ID, वा @username खोज्नुहोस्...',
    'scam_alert_title'      : 'घोटाला अलर्ट',
    'scam_alert_body'       : 'यस हप्ता काठमाडौंमा नक्कली TikTok विक्रेताहरूका धेरै रिपोर्टहरू। भुक्तानी गर्नु अघि सधैं प्रमाणित गर्नुहोस्।',
    'quick_actions'         : 'द्रुत कार्यहरू',
    'search_seller'         : 'विक्रेता\nखोज्नुहोस्',
    'report_fraud'          : 'धोखाधडी\nरिपोर्ट',
    'register_business'     : 'व्यवसाय\nदर्ता',
    'community_stats'       : 'समुदाय तथ्याङ्क',
    'sellers_verified'      : 'विक्रेता\nप्रमाणित',
    'scam_reports'          : 'घोटाला\nरिपोर्ट',
    'scams_prevented'       : 'घोटाला\nरोकियो',
    'how_it_works'          : 'कसरी काम गर्छ',
    'step1_title'           : 'खोज्नुहोस्',
    'step1_sub'             : 'विक्रेताको फोन, eSewa ID वा नाम लेख्नुहोस्',
    'step2_title'           : 'जाँच गर्नुहोस्',
    'step2_sub'             : 'ट्रस्ट स्कोर र रिपोर्टहरू हेर्नुहोस्',
    'step3_title'           : 'निर्णय गर्नुहोस्',
    'step3_sub'             : 'आत्मविश्वासले किन्नुहोस् वा रिपोर्ट गर्नुहोस्',
    'no_seller_found'       : 'विक्रेता भेटिएन',
    'no_seller_body'        : 'यो विक्रेता हाम्रो डेटाबेसमा छैन। भुक्तानी गर्नु अघि सावधान रहनुहोस्।',
    'report_this_seller'    : 'यो विक्रेता रिपोर्ट गर्नुहोस्',
    'home'                  : 'गृहपृष्ठ',
    'my_business'           : 'मेरो व्यवसाय',

    // ── Trust badges ─────────────────────────────────────────────────────────────
    'trusted'               : 'विश्वसनीय',
    'unverified'            : 'अप्रमाणित',
    'high_risk'             : 'उच्च जोखिम',
    'trust_score'           : 'ट्रस्ट स्कोर',
    'verified_badge'        : 'प्रमाणित',
    'reports_count'         : 'रिपोर्टहरू',
    'reviews_count'         : 'समीक्षाहरू',
    'orders_count'          : 'अर्डरहरू',

    // ── Report form ───────────────────────────────────────────────────────────────
    'who_scammed'           : 'कसले ठग्यो?',
    'who_scammed_sub'       : 'विक्रेताको बारेमा थाहा भएको कुनै पनि पहिचानकर्ता लेख्नुहोस्',
    'phone_number'          : 'फोन नम्बर *',
    'esewa_id'              : 'eSewa / Khalti ID',
    'social_handle'         : 'सोसल मिडिया ह्यान्डल',
    'platform'              : 'प्लेटफर्म',
    'what_happened'         : 'के भयो?',
    'what_happened_sub'     : 'घटनाको विस्तृत विवरण दिनुहोस्',
    'amount_lost'           : 'गुमेको रकम (रु)',
    'incident_type'         : 'घटनाको प्रकार *',
    'description'           : 'विवरण *',
    'description_hint'      : 'के भयो विस्तृत रूपमा लेख्नुहोस् (कम्तीमा ५० अक्षर)...',
    'incident_date'         : 'घटनाको मिति',
    'declaration_check'     : 'म पुष्टि गर्छु कि यो रिपोर्ट सत्य छ र मेरो व्यक्तिगत अनुभवमा आधारित छ।',
    'evidence_upload'       : 'प्रमाण अपलोड',
    'evidence_sub'          : 'स्क्रिनसटले तपाईंको रिपोर्ट छिटो प्रमाणित गर्न मद्दत गर्छ',
    'payment_screenshot'    : 'भुक्तानी स्क्रिनसट',
    'chat_screenshot'       : 'च्याट स्क्रिनसट',
    'add_screenshot'        : 'स्क्रिनसट थप्न थिच्नुहोस्',
    'evidence_types'        : 'भुक्तानी प्रमाण, च्याट स्क्रिनसट, उत्पादन फोटो',
    'report_submitted'      : 'रिपोर्ट पेश गरियो!',
    'report_submitted_body' : 'तपाईंको रिपोर्ट प्राप्त भयो। हाम्रो टिमले २-३ कार्यदिनभित्र समीक्षा गर्नेछ।',
    'report_id_label'       : 'तपाईंको रिपोर्ट ID',
    'seller_details'        : 'विक्रेता विवरण',
    'incident_info'         : 'घटना जानकारी',
    'evidence'              : 'प्रमाण',

    // ── Business registration ─────────────────────────────────────────────────────
    'reg_title'             : 'व्यवसाय दर्ता गर्नुहोस्',
    'reg_step1_title'       : 'व्यवसाय',
    'reg_step2_title'       : 'सोसल मिडिया',
    'reg_step3_title'       : 'पुष्टि',
    'business_name'         : 'व्यवसायको नाम *',
    'business_category'     : 'श्रेणी *',
    'business_description'  : 'व्यवसायको विवरण',
    'business_description_hint': 'खरिदारहरूलाई आफ्नो व्यवसायको बारेमा बताउनुहोस् (५०-५०० अक्षर)...',
    'esewa_recommended'     : 'eSewa ID (सिफारिस गरिएको)',
    'tiktok_handle'         : 'TikTok ह्यान्डल',
    'instagram_handle'      : 'Instagram ह्यान्डल',
    'facebook_page'         : 'Facebook पेज',
    'declaration_business'  : 'म पुष्टि गर्छु कि यो जानकारी सही छ र म यी खाताहरूको अधिकृत मालिक हुँ।',
    'reg_submitted'         : 'दर्ता पेश गरियो!',
    'reg_submitted_body'    : 'तपाईंको व्यवसाय प्रमाणीकरणका लागि पेश गरिएको छ। ४८ घण्टाभित्र ट्रस्ट स्कोर प्राप्त हुनेछ।',

    // ── Dashboard ─────────────────────────────────────────────────────────────────
    'dashboard_title'       : 'व्यवसाय ड्यासबोर्ड',
    'verification_steps'    : 'प्रमाणीकरण जाँचसूची',
    'recent_activity'       : 'हालका गतिविधिहरू',
    'your_reports'          : 'तपाईंविरुद्धका रिपोर्टहरू',
    'respond'               : 'प्रतिक्रिया दिनुहोस्',
    'share_profile'         : 'प्रोफाइल सेयर',
    'request_verification'  : 'प्रमाणीकरण अनुरोध',
    'profile_views_today'   : 'आजका प्रोफाइल दृश्यहरू',
    'avg_rating'            : 'औसत रेटिङ',

    // ── Language ──────────────────────────────────────────────────────────────────
    'select_language'       : 'Select Language / भाषा छान्नुहोस्',
    'continue_english'      : 'Continue in English',
    'continue_nepali'       : 'नेपालीमा जारी राख्नुहोस्',

    // ── Chatbot ───────────────────────────────────────────────────────────────────
    'chatbot_label'         : 'सहायता',
    'chatbot_title'         : 'SafeBuy सहायक',
    'chatbot_online'        : 'अनलाइन',
    'chatbot_greeting'      : 'नमस्ते! 👋 म SafeBuy Nepal सहायक हुँ। तलका विषयमध्ये एउटा छान्नुहोस् वा आफ्नो प्रश्न लेख्नुहोस्।',
    'chatbot_fallback'      : 'माफ गर्नुहोस्, बुझिनँ। कृपया तलका विकल्पहरूबाट छान्नुहोस्।',
    'chatbot_type_hint'     : 'आफ्नो प्रश्न लेख्नुहोस्...',
    'quick_questions'       : 'प्रश्नहरू:',

    // ── Incident type display ──────────────────────────────────────────────────────
    'inc_no_delivery'       : 'सामान डेलिभरी भएन',
    'inc_wrong_item'        : 'गलत सामान पठाइयो',
    'inc_fake_product'      : 'नक्कली उत्पादन',
    'inc_payment_issue'     : 'भुक्तानी लिएर कुनै प्रतिक्रिया छैन',
    'inc_impersonation'     : 'खाता नक्कल',
    'inc_other'             : 'अन्य',

    // ── Popup messages ────────────────────────────────────────────────────────────
    'success_report'        : 'रिपोर्ट सफलतापूर्वक पेश गरियो!',
    'success_review'        : 'समीक्षा पेश गरियो!',
    'success_kyc'           : 'KYC समीक्षाका लागि पेश गरियो',
    'success_signout'       : 'सफलतापूर्वक साइन आउट भयो',
    'warning_auth_required' : 'जारी राख्न साइन इन गर्नुस्',
    'error_upload'          : 'अपलोड असफल भयो। जडान जाँचेर पुनः प्रयास गर्नुहोस्।',
    'error_load'            : 'डाटा लोड गर्न सकिएन। पुनः प्रयास गर्नुहोस्।',

    // ── KYC ───────────────────────────────────────────────────────────────────────
    'kyc_title'             : 'SafeBuy प्रमाणित बन्नुहोस्',
    'kyc_subtitle'          : 'आफ्नो व्यवसाय जोगाउनुहोस् र विश्वास बनाउनुहोस्',
    'kyc_start'             : 'प्रमाणीकरण सुरु गर्नुहोस्',
    'kyc_tier_basic'        : 'आधारभूत',
    'kyc_tier_verified'     : 'प्रमाणित',
    'kyc_tier_premium'      : 'प्रिमियम',
    'kyc_link_gmail'        : 'Gmail खाता जोड्नुहोस्',
    'kyc_upload_qr'         : 'आफ्नो eSewa QR कोड अपलोड गर्नुहोस्',
    'kyc_selfie_title'      : 'नागरिकतासहित सेल्फी',
    'kyc_pan_title'         : 'PAN कार्ड अपलोड',
    'kyc_location_title'    : 'व्यवसाय स्थानका फोटोहरू',
    'kyc_submitted'         : 'KYC समीक्षाका लागि पेश गरियो',
    'kyc_review_time'       : 'हाम्रो टिमले २४-४८ घण्टाभित्र समीक्षा गर्नेछ',
    'kyc_qr_locked'         : 'भुक्तानी QR — SafeBuy Nepal द्वारा लक गरिएको',
    'kyc_request_qr_change' : 'QR परिवर्तन अनुरोध',

    // ── Leaderboard ───────────────────────────────────────────────────────────────
    'leaderboard_title'     : 'मासिक लिडरबोर्ड',
    'leaderboard_subtitle'  : 'यस महिनाका उत्कृष्ट प्रमाणित विक्रेता',
    'leaderboard_this_month': 'यो महिना',
    'leaderboard_last_month': 'गत महिना',
    'leaderboard_all_time'  : 'सबै समय',
    'leaderboard_empty'     : 'यस अवधिको लागि कुनै र्‍याङ्किङ छैन',

    // ── Reviews ───────────────────────────────────────────────────────────────────
    'review_write'          : 'समीक्षा लेख्नुहोस्',
    'review_product_name'   : 'तपाईंले के किन्नुभयो?',
    'review_rating'         : 'तपाईंको रेटिङ',
    'review_experience'     : 'समग्र अनुभव',
    'review_verified'       : 'प्रमाणित खरिद',
    'review_top'            : 'उत्कृष्ट समीक्षा',

    // ── Guide ─────────────────────────────────────────────────────────────────────
    'guide_title'           : 'कसरी काम गर्छ',
    'guide_for_buyers'      : 'खरिदारका लागि',
    'guide_for_sellers'     : 'विक्रेताका लागि',
    'guide_about'           : 'SafeBuy बारे',

    // ── Scam news ─────────────────────────────────────────────────────────────────
    'scam_news_title'       : 'नेपाल ठगी रिपोर्टहरू',
    'scam_news_cases'       : 'घटनाहरू',
    'scam_news_stats'       : 'तथ्याङ्क',
    'scam_news_rights'      : 'तपाईंका अधिकार',
    'scam_news_read_more'   : 'थप पढ्नुहोस्',
    'scam_news_show_less'   : 'कम देखाउनुहोस्',
    'scam_news_lesson'      : 'पाठ',

    // ── Search ────────────────────────────────────────────────────────────────────
    'search_title'          : 'विक्रेता प्रमाणित गर्नुहोस्',
    'search_member_since'   : 'सदस्य बनेको',
    'search_verified_until' : 'प्रमाणित अवधि',
    'search_overdue'        : 'पुनः प्रमाणीकरण बाँकी',
    'search_view_profile'   : 'पूरा प्रोफाइल हेर्नुहोस्',
    'search_report_seller'  : 'यो विक्रेता रिपोर्ट गर्नुहोस्',
    'search_sign_in_report' : 'रिपोर्ट गर्न साइन इन गर्नुहोस्',
    'search_not_found'      : 'यो जानकारीसँग कुनै विक्रेता भेटिएन',
  };

  static String get(String key, String lang) =>
      (lang == 'ne' ? _ne[key] : _en[key]) ?? _en[key] ?? key;

  /// Returns the display label for an incident type key.
  static String incidentTypeLabel(String type, String lang) =>
      get('inc_$type', lang);
}
